[database]
    name            = "todo"
    access_type     = "password"
    username        = "root"
    password        = ""
    [database.options]
        host        = "127.0.0.1"
        port        = 3306
        dialect     = "mysql"